package sample.data.jpa.domain;

// Generated Apr 11, 2007 11:39:28 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Version;

/**
 * Tank generated by hbm2java
 */
@Entity
public class Account implements java.io.Serializable {
    @Id
    @GeneratedValue
    private int id;

    private String accountName;

    private BigDecimal currentVolume;

    private Date currentVolumeTimestamp;

    @Version
    private int version;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public BigDecimal getCurrentVolume() {
        return currentVolume;
    }

    public void setCurrentVolume(BigDecimal currentVolume) {
        this.currentVolume = currentVolume;
    }

    public Date getCurrentVolumeTimestamp() {
        return currentVolumeTimestamp;
    }

    public void setCurrentVolumeTimestamp(Date currentVolumeTimestamp) {
        this.currentVolumeTimestamp = currentVolumeTimestamp;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }
}
